### ISSUE TITLE
Relax Python >=3.11 requirement + setup tox

### ISSUE THREAD

**Issue by greywidget** [PyBites-Open-Source/search#14]
From a quick chat in PDM slack with Bob, I think that the requirement Python >=3.11 is unnecessarily strict.

Unless there are technical reasons, relaxing this requirement will make it easier for more folks to benefit from this great tool

**Comment by bbelderbos** [comment]
Thanks @greywidget I will get to this this week: loosen Python version and set up tox to test various versions.

**Comment by bbelderbos** [comment]
done: https://github.com/PyBites-Open-Source/search/pull/15
