### ISSUE TITLE
add some more documentation how to setup this package for local dev

### ISSUE THREAD

**Issue by bbelderbos** [PyBites-Open-Source/search#20]

**Comment by bbelderbos** [comment]
To do dev work on this repo:

1. Check out the repo and make a virtual env and activate it:

```
$ git clone git@github.com:PyBites-Open-Source/search.git
$ cd search
√ search (main) $ python3 -m venv venv && source venv/bin/activate
```

2. Install the regular + test + linting dependencies:

``` 
(venv) √ search (main) $ pip install .
...
Successfully built pybites_search
...
(venv) √ search (main) $ pip install ".[test]"
```

3. Run the tests

```
(venv) √ search (main) $ tox
...
  py39: OK (15.89=setup[14.49]+cmd[1.40] seconds)
  py310: OK (13.22=setup[11.80]+cmd[1.42] seconds)
  py311: OK (10.42=setup[9.41]+cmd[1.01] seconds)
  congratulations :) (39.61 seconds)
```

4. Code / have fun ...

**Comment by greywidget** [comment]
@bbelderbos Instructions work OK thanks.
On windows the virtual environment build would be a bit different:
`py -3 -m venv venv && venv\scripts\activate`
but I guess we'd expect anyone wanting a dev environment to be able to figure that out.

Isn't it a better practice to run the installs as:
- `python -m pip install .`
- `python -m pip install ".[test,lint]"`

As an aside, one test is failing for me, it is to do with the character used to render the table borders. I'll raise an issue.

**Comment by bbelderbos** [comment]
Yes good point on `-m`, I will change that in the instruction which I will add to the Readme to close out this issue. The quotes around the second command I needed for zsh by the way. Yep please log and I will fix that as well. Let me know if you're happy for me to change in previous changes as well. I think with the `all` options + caching there is no way back, it makes the tool much better :) - thanks.
