### ISSUE TITLE
Search All might look cleaner in a single table

### ISSUE THREAD

**Issue by greywidget** [PyBites-Open-Source/search#28]
Peforming a `search all <search term>` potentially produces output of multiple tables of varying column widths.

It might be nicer to default to all results in a single table with an exta column or header row to identify the channel.

Perhaps a `--no-group` or similar option to provide separate tables as now.

Some related ideas:
- rich Tables can have their own headers: [table_options](https://rich.readthedocs.io/en/latest/tables.html#table-options) so we could perhaps utilise that rather than outputting a seperate piece of text for the header
- If we like the combined table idea, would it make sense to have a new CombinedSearch class with its own `show_matches` method, as the combined table might have an extra colunm for channel (tip/youtube etc) or additional header row to demark channels. If we like the `--no-group` idea then under that scenario the CombinedSearch class could just iterate the the default `show_matches` for each class

**Comment by bbelderbos** [comment]
@greywidget so we got a combined table, do you still want to do `--no-group`? I am happy with how things are now (1.0.0) - thanks!

**Comment by greywidget** [comment]
OK, after a bit of a play, I think it messes the code too much for something we don't currently have a requirement for. I'm happy to leave it as it is for now - I think there are better gains to be had elsewhere.

**Comment by bbelderbos** [comment]
OK thanks for confirming.
