### ISSUE TITLE
Should we reduce some of the repeated code in cli.py (add some Typer cli testing as well)

### ISSUE THREAD

**Issue by greywidget** [PyBites-Open-Source/search#29]
In the interests of the DRY principle should we consider creating a wrapper function to reduce some of the repetition in `cli.py`

Something along the lines of:

```
def search_content(searcher, search, extra_nl=False):
    results = searcher.match_content(search)
    searcher.show_matches(results, extra_nl=False)


@app.command()
def article(search: str):
    search_content(ArticleSearch(), search)


@app.command()
def bite(search: str):
    search_content(BiteSearch(), search)
```

**Comment by bbelderbos** [comment]
Happy to do so, also I skipped cli.py for coverage, maybe we should actually write a bit of Typer test code here.

**Comment by bbelderbos** [comment]
Thanks @greywidget - PR: https://github.com/PyBites-Open-Source/search/pull/35
